// Generated by scripts/music-manifest.ts from audio/music/*.mp3 - do not edit by hand (bun run music:manifest).
import m0 from '../audio/music/net_calm.mp3'
import m1 from '../audio/music/net_combat.mp3'
import m2 from '../audio/music/net_tension.mp3'

export const MUSIC_FILES: Record<string, string> = {
  'net_calm': m0,
  'net_combat': m1,
  'net_tension': m2,
}
