// Generated by scripts/music-manifest.ts from audio/music/*.mp3 - do not edit by hand (bun run music:manifest).
import m0 from '../audio/music/hack.mp3'
import m1 from '../audio/music/menu.mp3'
import m2 from '../audio/music/net_calm.mp3'
import m3 from '../audio/music/net_combat.mp3'
import m4 from '../audio/music/net_tension.mp3'
import m5 from '../audio/music/office.mp3'
import m6 from '../audio/music/room.mp3'
import m7 from '../audio/music/sting_death.mp3'
import m8 from '../audio/music/sting_end.mp3'
import m9 from '../audio/music/sting_win.mp3'

export const MUSIC_FILES: Record<string, string> = {
  'hack': m0,
  'menu': m1,
  'net_calm': m2,
  'net_combat': m3,
  'net_tension': m4,
  'office': m5,
  'room': m6,
  'sting_death': m7,
  'sting_end': m8,
  'sting_win': m9,
}
