// Every picture this test may use, by file name. Bun bundles only static imports, so a new picture needs one line here;
// config.json picks which ones are actually used (plate set, close-ups), so swapping a set is a config change.
import cu1 from '../../art/generated/CU1e-water.jpg'
import cu2 from '../../art/generated/CU2e-noodles.jpg'
import cu3 from '../../art/generated/CU3d-tablet.jpg'
import cu4 from '../../art/generated/CU4g-vr-inside.jpg'
import cu4Mask from '../../art/generated/CU4g-vr-inside-mask.png'
import cu5 from '../../art/generated/CU5c-window.jpg'
import fp4Depth from '../../art/generated/FP4-room-fp-depth.png'
import fp4MasksA from '../../art/generated/FP4-room-fp-masks-a.png'
import fp4MasksB from '../../art/generated/FP4-room-fp-masks-b.png'
import fp4 from '../../art/generated/FP4-room-fp.jpg'
import n1 from '../../art/generated/N1-news-layoffs.jpg'
import nn1 from '../../art/generated/NN1b-net-corridor.jpg'

const ART: Record<string, string> = {
  'CU1e-water.jpg': cu1,
  'CU2e-noodles.jpg': cu2,
  'CU3d-tablet.jpg': cu3,
  'CU4g-vr-inside.jpg': cu4,
  'CU4g-vr-inside-mask.png': cu4Mask,
  'CU5c-window.jpg': cu5,
  'FP4-room-fp.jpg': fp4,
  'FP4-room-fp-depth.png': fp4Depth,
  'FP4-room-fp-masks-a.png': fp4MasksA,
  'FP4-room-fp-masks-b.png': fp4MasksB,
  'N1-news-layoffs.jpg': n1,
  'NN1b-net-corridor.jpg': nn1,
}

/** URL of a picture from art/generated by its file name (as written in config.json). */
export function art(name: string): string {
  const url = ART[name]
  if (!url) throw new Error(`room-fp: "${name}" is not imported in tests/room-fp/art.ts`)
  return url
}
