// Lists audio/music/*.mp3 into view/music-files.ts (imports, so the bundler ships them). The folder may be empty: the
// game then plays no music. Run it after adding or removing a music file (`bun run music:manifest`); `play`, `build`
// and `check` run it first. Pass --check to only verify the file is up to date.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const root = import.meta.dir.replace(/\/scripts$/, '')
const dir = `${root}/audio/music`
const out = `${root}/view/music-files.ts`
let files: string[] = []
try {
  files = readdirSync(dir)
    .filter((f) => f.endsWith('.mp3'))
    .sort()
} catch {
  files = []
}
const lines = [
  '// Generated by scripts/music-manifest.ts from audio/music/*.mp3 - do not edit by hand (bun run music:manifest).',
  ...files.map((f, i) => `import m${i} from '../audio/music/${f}'`),
  '',
  'export const MUSIC_FILES: Record<string, string> = {',
  ...files.map((f, i) => `  '${f.replace(/\.mp3$/, '')}': m${i},`),
  '}',
  '',
]
const text = lines.join('\n')
let old = ''
try {
  old = readFileSync(out, 'utf8')
} catch {
  // not generated yet
}
if (Bun.argv.includes('--check')) {
  if (old !== text) throw new Error('view/music-files.ts is out of date: run bun run music:manifest')
  console.log(`music-manifest: up to date (${files.length} files)`)
} else {
  if (old !== text) writeFileSync(out, text)
  console.log(`music-manifest: ${files.length} files`)
}
